#  To run interactive, Comment out command and run docker-compose run --rm aux
version: '3'

services:
    auxiliary:

      image: aux:latest
      
      command: python3 /src/aux.py
      
      stdin_open: true # docker run -i

      tty: true        # docker run -t

      devices:
        - "/dev/ttyUSB0"
        - "/dev/ttyUSB1"
        - "/dev/ttyUSB2"
        - "/dev/ttyUSB3"

      privileged: true
      
      build: ./

       
      volumes:
        - ./src:/src

      # cap_add:
      #   - ALL

      environment:            
        SERVER_PUB_LOGIC_CONNECT_URI: tcp://host.docker.internal:5007          # PUB to Logic 
        AUX_PULSE_MESSAGE: ana_aux_pulse
      
      extra_hosts:
        - "host.docker.internal:host-gateway"



